name       : python-easygui
version    : 0.98.2
release    : 6
source     :
    - https://files.pythonhosted.org/packages/source/e/easygui/easygui-0.98.2.tar.gz : 073f728ca88a77b74f404446fb8ec3004945427677c5618bd00f70c1b999fef2
homepage   : https://github.com/robertlugg/easygui
license    : BSD-3-Clause
component  : programming.python
summary    : Very simple, very easy GUI programming in Python
description: |
    EasyGUI is a module for very simple, very easy GUI programming in Python. EasyGUI is different from other GUI libraries in that EasyGUI is NOT event-driven. Instead, all GUI interactions are invoked by simple function calls.
rundeps    :
    - python3-tkinter
setup      : |
    cp README.txt README.md
build      : |
    %python3_setup
install    : |
    %python3_install
