name       : python-easygui
version    : 0.98.1
release    : 4
source     :
    - https://github.com/robertlugg/easygui/archive/0.98.1.tar.gz : b46d1f06b85a2de2b15129906d21bb42bc66a6e800315fed57e634cf151fc083
homepage   : https://github.com/robertlugg/easygui
license    : BSD-3-Clause
component  : programming.python
summary    : Very simple, very easy GUI programming in Python
description: |
    EasyGUI is a module for very simple, very easy GUI programming in Python. EasyGUI is different from other GUI libraries in that EasyGUI is NOT event-driven. Instead, all GUI interactions are invoked by simple function calls.
rundeps    :
    - python3-tkinter
build      : |
    %python3_setup
install    : |
    %python3_install
